version: "3.5"

services:
  web-application:
    container_name: web-application
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - FLAG="RSASM{i3O2c53s39r0rUdMIN2Y0LpDG4OEMG20}"